Iamge_WebP/Models/DbContexte.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Iamge_WebP.Models
{
    public class DbContexte:DbContext
    {
        public DbContexte(DbContextOptions<DbContexte> option):base(option) 
        {
            
        }

        public DbSet<Item> Items { get; set; }
    }
}

Iamge_WebP/Models/ErrorViewModel.cs
using System;

namespace Iamge_WebP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Iamge_WebP/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Iamge_WebP.Models
{
    public class Item
    {
        public int id { get; set; }
        public string ItemName { get; set; }
        public string ImagePath { get; set; }
        public string Descreption { get; set; }
    }
}

Iamge_WebP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Iamge_WebP.Models;

namespace Iamge_WebP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Iamge_WebP/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Iamge_WebP.Models;
using ImageProcessor;
using ImageProcessor.Plugins.WebP.Imaging.Formats;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;

namespace Iamge_WebP.Controllers
{
    public class ItemController : Controller
    {
        private readonly IHostingEnvironment hostingEnvironment;

        private DbContexte db;

        public ItemController(IHostingEnvironment _environment  ,DbContexte _db)
        {
            this.hostingEnvironment = _environment;
            this.db = _db;
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Models.Item items, IFormFile image)
        {
            // Check if valid image type (can be extended with more rigorous checks)
            if (image == null || image.Length < 1)
            {
                return View();
            }



            string[] allowedImageTypes = new string[] { "image/jpeg", "image/png" };
            if (!allowedImageTypes.Contains(image.ContentType.ToLower()))
            {
                return View();
            }

            // Prepare paths for saving images
            string imagesPath = Path.Combine(hostingEnvironment.ContentRootPath, "wwwroot/images");
            string webPFileName = Path.GetFileNameWithoutExtension(image.FileName) + ".webp";            
            string webPImagePath = Path.Combine(imagesPath, webPFileName);



            items.ImagePath ="~/Images/"+ webPFileName;

            if (ModelState.IsValid)
            {
                FileStream webPFileStream = new FileStream(webPImagePath, FileMode.Create);

                ImageFactory imageFactory = new ImageFactory(preserveExifData: false);

                imageFactory.Load(image.OpenReadStream())
                    .Format(new WebPFormat())
                    .Quality(50)
                    .Save(webPFileStream);



                db.Items.Add(items);
                db.SaveChanges();
            }


            return RedirectToActionPermanent("Index");

        }


        public IActionResult Index()
        {



            return View(db.Items.ToList());
        }

      
      
    }
}

Iamge_WebP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Iamge_WebP/Views/Item/Create.cshtml
@model Iamge_WebP.Models.Item

@{
    ViewData["Title"] = "Create";
}


<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Item Entry</div>
        <div class="panel-body">

  

<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descreption" class="control-label"></label>
                <input asp-for="Descreption" class="form-control" />
                <span asp-validation-for="Descreption" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <div class="form-group">
                    <img src="~/pic_default.png" id="uploadPreview" height="180" width="140" class="border-info" />
                </div>
                <label class="control-label">Image</label>
                <input type="file" id="uploadImage" onchange="PreviewImage()" name="image"/>
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>

          
        </div>

    </div>

        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
</form>
    

        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script type="text/javascript">

    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };

</script>

Iamge_WebP/Views/Item/Index.cshtml
@model IEnumerable<Iamge_WebP.Models.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<a class="btn btn-info" asp-action="Create">Create New</a>
<br />
<div class="row">
    @foreach (var item in Model)
{
    <div class="col-md-4 col-xl-4">
        <div class="card overflow-hidden">
           
            <img src="@Url.Content(item.ImagePath)" width="80" height="99"/>
            <div class="card-body">
                <h5 class="card-title mb-3">@item.ItemName</h5>
                <p class="card-text">@item.Descreption</p>
                <a href="javascript:void(0);" class="btn btn-primary">Read More</a>
            </div>
        </div>
    </div>
}
</div>

Iamge_WebP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Iamge_WebP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Iamge_WebP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Iamge_WebP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>